In [2]:
#11program
row = 5
for i in range(0, row):
    for j in range(0, i + 1):
        print("*", end=' ')
    print("\r")

* 
* * 
* * * 
* * * * 
* * * * * 


In [5]:
#12program
import re

str1 = str(input("enter a string:"))

print ("The input string is : ")
print(str1)

op = re.sub('[\W_]+', '', str1)

print ("The cleared string is :")
print(op)

enter a string:p*y#t^h$o#n
The input string is : 
p*y#t^h$o#n
The cleared string is :
python


In [7]:
#13program
x=[21,25,55,90,87]
for i in x:
    if(i%5==0):
        print('the value is :',i)
    else :
        continue

the value is : 25
the value is : 55
the value is : 90


In [9]:
#14program
str1 = str(input("enter a string:"))
n=int(str1.count('hi'))
print("the string \"hi\" has appeared "+format(n)+" times")

enter a string:hi hi hi
the string "hi" has appeared 3 times


In [10]:
#15program
row = 6
for i in range(row):
    
    for j in range(i):
        print(i, end=' ')
    print('')


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [11]:
list
#python program to interchange first and last elements in list
listt = []
n = int(input("Enter number of elements in the list : "))
for i in range(0, n):
   print("Enter the "+format(i+1)+"th element:")
   elm = int(input())
   listt.append(elm)
first=int(input("enter the element that you want in the first place of the list:"))
last=int(input("enter the element that you want in the first place of the list:"))
listt[0]=first
listt[-1]=last
print(listt)

Enter number of elements in the list : 5
Enter the 1th element:
22
Enter the 2th element:
2
Enter the 3th element:
3
Enter the 4th element:
5
Enter the 5th element:
6
enter the element that you want in the first place of the list:3
enter the element that you want in the first place of the list:5
[3, 2, 3, 5, 5]


In [12]:
#program to swap two elements
def swapL(sl,pos1,pos2):
    n = len(sl)     
    temp = sl[pos1]
    sl[pos1] = sl[pos2]
    sl[pos2] = temp
    return sl      

m= [1, 14, 4, 6, 6, 15]
pos1= 3
pos2= 5

print(m)
print("Swapped list: ",swapL(m,pos1-1,pos2-1))

[1, 14, 4, 6, 6, 15]
Swapped list:  [1, 14, 6, 6, 4, 15]


In [14]:
#ways to find length
list1=[1,2,3,'wee','bangtan',6,7]
n=0
print("length of the list=",len(list1))
for i in list1:
    n=n+1
print("the length of the list is",n)

length of the list= 7
the length of the list is 7


In [16]:
#maximum of two nos
n = [2,4,8,1,274]

  
maxi = max(n )
print(maxi)

274


In [17]:
#minimum of two nos
n = [274,390,844,69]

  
mini = min(n)
print(mini)

69


In [19]:
#STRING
#check whether the string is symmetrical or palindrome
str2=str1[::-1]

if str1==str2:
    print("the entered string is a palindrome")
else:
    print("the entered string is not a palindrome")


the entered string is not a palindrome


In [21]:
#reverse words in string
string = "annyeong hasimnikka!"

n = string.split()[::-1]
l = []
for i in n:
    
    l.append(i)

print(" ".join(l))

hasimnikka! annyeong


In [22]:
#ways to remove i'th character from string
str1=str(input("enter a string:"))
i=int(input("enter the position of the element you want to remove:"))
str2 = str1[:i-1] +  str1[i:] 
print ("String after removal of character: " + str2)

enter a string:programming
enter the position of the element you want to remove:9
String after removal of character: programmng


In [23]:
#tuples
#size of the tuple
tuplee = []
n = int(input("Enter number of elements in the tuple : "))
for i in range(0, n):
   print("Enter the "+format(i+1)+"th element:")
   elm = (input())
   tuplee.append(elm)
tuple1=tuple(tuplee)
print("size of the tuple is:", tuple1.__sizeof__(),"bytes")
print("the length of the tuple is:",len(tuple1))


Enter number of elements in the tuple : 5
Enter the 1th element:
1
Enter the 2th element:
2
Enter the 3th element:
r4
Enter the 4th element:
66
Enter the 5th element:
6
size of the tuple is: 64 bytes
the length of the tuple is: 5


In [24]:
#maximum and minimum k elements
n=(0,3,9,2,4)
x=max(n)
y=min(n)
print(x)
print(y)

9
0


In [26]:
#sum of tuple elements
tuplee = []
sum=0
n = int(input("Enter number of elements in the tuple : "))
for i in range(0, n):
   print("Enter the "+format(i+1)+"th element:")
   elm = int(input())
   tuplee.append(elm)
tuple1=tuple(tuplee)
for i in tuple1:
    sum=sum+i
print("the sum is:", sum)


Enter number of elements in the tuple : 5
Enter the 1th element:
2
Enter the 2th element:
33
Enter the 3th element:
45
Enter the 4th element:
12
Enter the 5th element:
97
the sum is: 189


In [28]:
#dictionary
#sort python dictionaries
d={"key4":"8","key1":"2","key4":"1"}
print(sorted(d))

['key1', 'key4']


In [29]:
#dictionary with keys having multiple inputs
a, b, c = 19, 3, 4
dict1 = {}
dict1[a, b, c] = a + b * c

a, b, c = 5, 16, 4
dict1[a, b, c] = a - b//c

print("The dictionary is :")
print(dict1)


The dictionary is :
{(19, 3, 4): 31, (5, 16, 4): 1}


In [30]:
#SET
#size of the set
a={7,2,1,5}
a.__sizeof__()

200

In [31]:
#iterate over a set
sett = {"a", "b", 1,("a",1,2)}
print("the size of the set is",sett.__sizeof__(),"bytes")
print("the length of the set is", len(sett))


the size of the set is 200 bytes
the length of the set is 4


In [33]:
#MATRIX
#assigning subsequent rows to matrix first row elements
list = [[4,7,5], [15,10,11], [4,3,6], [18, 1, 14]]
print("The original list : ",str(list))
res = {list[0][ele] :  list[ele + 1] for ele in range(len(list) - 1)}
print("The Assigned Matrix : ", str(res))

The original list :  [[4, 7, 5], [15, 10, 11], [4, 3, 6], [18, 1, 14]]
The Assigned Matrix :  {4: [15, 10, 11], 7: [4, 3, 6], 5: [18, 1, 14]}


In [36]:
#adding and substracting matrices
import numpy as np
A = np.array([[3,5], [4,9]])
B = np.array([[6, 5], [5, 2]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))


Printing elements of first matrix
[[3 5]
 [4 9]]
Printing elements of second matrix
[[6 5]
 [5 2]]
Addition of two matrix
[[ 9 10]
 [ 9 11]]


In [37]:
#functions
#list of parameters name
def mul(a, b):
    return a*b
import inspect as ip 
print(ip.signature(mul))

(a, b)


In [38]:
#print multiple arguments
def a(name, nam1):
    print("hi", name +', ' , nam1)
a("anneyong", "hansimnikka")

hi anneyong,  hansimnikka
